### ISSUE TITLE
When trying to enable the addon an error occurs.

### ISSUE THREAD

**Issue by Taneblade** [nerk987/txa_ant#16]
I downloaded and installed the add on but when I click enable an error occurs. Here is what it says, maybe you can make sense of this: 
```
Traceback (most recent call last):
  File "E:\Blender\4.0\scripts\modules\addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
  File "E:\Blender\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\t\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\txa_ant-master\__init__.py", line 47, in <module>
    from txa_ant import add_mesh_ant_landscape
ModuleNotFoundError: No module named 'txa_ant'
```

**Comment by nerk987** [comment]
It sounds like the common problem when the Github source zip file is downloaded instead of the addon zip file.

Make sure you download the file "txa_ant_4_00_0.zip" from the link where it says:
Addon Download : txa_ant_4_00_0.zip
